import Link from "next/link";
import "../public/bootstrap/dist/css/bootstrap.css";
import Navbar from "./components/navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{ margin: "36px" }} className="pt-5">
          {children}
        </div>
      </body>
    </html>
  );
}
